abundance_samples:
- sample_S22282
- sample_S22205
assemblers:
- megahit
- metaspades
binning_samples:
- sample_S22282
- sample_S22205
envs:
  anvi: source activate shotgun-anvi
  humann2: source activate shotgun-humann2
  kraken: source activate shotgun-kraken
  qc: source activate shotgun-qc
  raw: source activate shotgun-qc
  metaphlan2: source activate shotgun-metaphlan2
  kraken: source activate shotgun-kraken
  shogun: source activate shotgun-shogun
  assemble: source activate shotgun-assemble
  mash: source activate shotgun-mash
mapping_assembler: metaspades
params:
  atropos: ' -a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A GATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGT
    -q 15 --minimum-length 100 --pair-filter any'
  humann2:
    humann2_aa_db: 'humann2_aa_db: /home/jgsanders/ref_data/humann2/uniref'
    humann2_nt_db: /home/jgsanders/ref_data/humann2/chocophlan
    metaphlan2_dir: /home/jgsanders/share/metaphlan2
    norms:
    - cpm
    - relab
    other: ''
  kraken:
    kraken_db: /home/qiz173/Databases/Kraken/stdb
  maxbin: -plotmarker
  metaphlan2:
    metaphlan2_dir: /home/jgsanders/git_sw/metaphlan2
  shogun: /home/a3tripat/test_shogun/shogun/bin/utree-search_gg /home/a3tripat/test_shogun/shogun/utree/genomes.small.gg.ctr
resources:
  centrifuge_base: /home/jgsanders/miniconda/envs/anvio2/centrifuge
  centrifuge_models: /home/jgsanders/miniconda/envs/anvio2/centrifuge/b+h+v/b+h+v
samples:
  sample_S22205:
    filter_db: ./test_data/phix
    forward:
    - ./test_data/test_reads/S22205_S104_L001_R1_001.fastq.gz
    reverse:
    - ./test_data/test_reads/S22205_S104_L001_R2_001.fastq.gz
  sample_S22282:
    filter_db: ./test_data/phix
    forward:
    - ./test_data/test_reads/S22282_S102_L001_R1_001.fastq.gz
    reverse:
    - ./test_data/test_reads/S22282_S102_L001_R2_001.fastq.gz
tmp_dir_root: ./
trimmer: atropos
